---
# Configuration file for the Bandit python security scanner
# https://bandit.readthedocs.io/en/latest/config.html

# Tests are first included by `tests`, and then excluded by `skips`.
# If `tests` is empty, all tests are considered included.

tests:

skips:
  # Skip "assert used" check since assertions are required in pytests
  - B101
  # Skip "pseudo-random generators not suitable for security"
  # b/c it's used for sample data
  - B311
