---

scheduler:
  handler: src/xfd_django/xfd_api/tasks/scheduler.handler
  timeout: 900
  events:
    - schedule: rate(5 minutes)
  reservedConcurrency: 1
  memorySize: 4096

syncdb:
  timeout: 900
  handler: src/xfd_django/xfd_api/tasks/run_syncdb.handler

syncmdl:
  timeout: 900
  handler: src/xfd_django/xfd_api/tasks/run_syncmdl.handler

bastion:
  timeout: 900
  handler: src/xfd_django/xfd_api/tasks/bastion.handler

checkUserExpiration:
  timeout: 300
  handler: src/xfd_django/xfd_api/tasks/checkUserExpiration.handler
  events:
    - schedule: cron(0 0 * * ? *)  # Runs every day at midnight

scanExecution:
  timeout: 900  # 15 minutes
  handler: src/xfd_django/xfd_api/tasks/scanExecution.handler
  memorySize: 4096

updateScanTaskStatus:
  handler: src/xfd_django/xfd_api/tasks/updateScanTaskStatus.handler
  events:
    - eventBridge:
        name: ${self:provider.stage}-updateScanTaskStatus
        pattern:
          source:
            - aws.ecs
          detail-type:
            - ECS Task State Change
          detail:
            clusterArn:
              - ${file(env.yml):${self:provider.stage}-ecs-cluster, ''}

infraOps:
  timeout: 900
  handler: src/xfd_django/xfd_api/tasks/infra_ops.handler

serviceStatsCache:
  handler: src/xfd_django/xfd_api/tasks/elasticache_tasks.populate_services_cache
  events:
    - schedule:
        rate: cron(0 0 * * ? *)  # This triggers the function every day it midnight

portStatsCache:
  handler: src/xfd_django/xfd_api/tasks/elasticache_tasks.populate_ports_cache
  events:
    - schedule:
        rate: cron(0 0 * * ? *)  # This triggers the function every day it midnight

numVulnsCache:
  handler: src/xfd_django/xfd_api/tasks/elasticache_tasks.populate_num_vulns_cache
  events:
    - schedule:
        rate: cron(0 0 * * ? *)  # This triggers the function every day it midnight

latestVulnsCache:
  handler: src/xfd_django/xfd_api/tasks/elasticache_tasks.populate_latest_vulns_cache
  events:
    - schedule:
        rate: cron(0 0 * * ? *)  # This triggers the function every day it midnight

mostCommonVulnsCache:
  handler: src/xfd_django/xfd_api/tasks/elasticache_tasks.populate_most_common_vulns_cache
  events:
    - schedule:
        rate: cron(0 0 * * ? *)  # This triggers the function every day it midnight

severityCache:
  handler: src/xfd_django/xfd_api/tasks/elasticache_tasks.populate_severity_cache
  events:
    - schedule:
        rate: cron(0 0 * * ? *)  # This triggers the function every day it midnight

byOrgCache:
  handler: src/xfd_django/xfd_api/tasks/elasticache_tasks.populate_by_org_cache
  events:
    - schedule:
        rate: cron(0 0 * * ? *)  # This triggers the function every day it midnight
