---
name: Regression Testing

on:
  deployment_status:

defaults:
  run:
    working-directory: ./playwright

jobs:
  test:
    environment: staging
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Set environment variables
        run: |
          echo "PW_XFD_2FA_ISSUER=${{ secrets.PW_XFD_2FA_ISSUER }}" >> .env
          echo "PW_XFD_2FA_SECRET=${{ secrets.PW_XFD_2FA_SECRET }}" >> .env
          echo "PW_XFD_PASSWORD=${{ secrets.PW_XFD_PASSWORD }}" >> .env
          echo "PW_XFD_USERNAME=${{ secrets.PW_XFD_USERNAME }}" >> .env
      - name: Run Playwright tests
        run: |
          npx playwright test
